server:
  port: 8088
    
spring: 
  profiles: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: yks-poseidon-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/